name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      cache:
        image: ghcr.io/sagikazarmark/blob-proxy:v0.1.1
        ports:
          - 8000:8000
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CACHE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHE_SECRET_ACCESS_KEY }}
          BUCKET: ${{ secrets.CACHE_BUCKET }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0
        with:
          profile: ci

      - name: Test
        run: plz test //...

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    needs: test

    services:
      vault:
        image: vault:1.4.2
        env:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf
        ports:
          - 8200

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Please cache
        uses: actions/cache@v2
        with:
          path: |
            .plz-cache
          key: ${{ runner.os }}-plz-v4-${{ hashFiles('**/BUILD', '**/BUILD.plz', '**/.plzconfig*', '**/go.mod', '**/go.sum', '**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-plz-v4-

      - name: Start kind cluster
        run: |
          ./pleasew -p --profile ci run ///pleasings2//tools/k8s:kind -- create cluster --kubeconfig $HOME/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Test
        run: |
          ./pleasew -p --profile ci build :kube-apiserver :etcd
          export TEST_ASSET_KUBE_APISERVER=$PWD/$(./pleasew -p --profile ci query output :kube-apiserver)
          export TEST_ASSET_ETCD=$PWD/$(./pleasew -p --profile ci query output :etcd)
          ./pleasew -p --profile ci test --include integration //...
        env:
          VAULT_ADDR: http://127.0.0.1:${{ job.services.vault.ports[8200] }}
          VAULT_TOKEN: 227e1cce-6bf7-30bb-2d2a-acc854318caf

      - name: Save Please log output
        uses: actions/upload-artifact@v1
        with:
          name: integration-test-log
          path: plz-out/log

  lint:
    name: Lint
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Please cache
        uses: actions/cache@v2
        with:
          path: |
            .plz-cache
          key: ${{ runner.os }}-plz-v4-${{ hashFiles('**/BUILD', '**/BUILD.plz', '**/.plzconfig*', '**/go.mod', '**/go.sum', '**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-plz-v4-

      - name: Go module cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Go build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go', '**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Lint
        run: ./pleasew -p --profile ci lint

      - name: Save Please log output
        uses: actions/upload-artifact@v1
        with:
          name: lint-log
          path: plz-out/log
